'use strict';

const Appointment = require('../models/Appointment');
const Patient = require('../models/Patient');
const Inventory = require('../models/Inventory');
const Report = require('../models/Report');
const HealthCenter = require('../models/HealthCenter');
const { REPORT_TYPES, REPORT_STATUS, APPOINTMENT_STATUS } = require('../config/constants');
const logger = require('../config/logger');

/**
 * Aggregate key metrics for a health centre over a date range.
 * Used both for report creation and summary generation.
 *
 * @param {string} centerId
 * @param {string|Date} startDate
 * @param {string|Date} endDate
 * @returns {Promise<object>}
 */
const aggregateMetrics = async (centerId, startDate, endDate) => {
  const start = new Date(startDate);
  const end = new Date(endDate);
  end.setHours(23, 59, 59, 999);

  const dateFilter = { date: { $gte: start, $lte: end } };
  const centerFilter = { healthCenter: centerId };

  const [
    appointmentStats,
    newPatients,
    inventoryUsage,
  ] = await Promise.all([
    Appointment.aggregate([
      { $match: { ...centerFilter, ...dateFilter } },
      {
        $group: {
          _id: null,
          total: { $sum: 1 },
          completed: { $sum: { $cond: [{ $eq: ['$status', APPOINTMENT_STATUS.COMPLETED] }, 1, 0] } },
          cancelled: { $sum: { $cond: [{ $eq: ['$status', APPOINTMENT_STATUS.CANCELLED] }, 1, 0] } },
          noShow: { $sum: { $cond: [{ $eq: ['$status', 'no-show'] }, 1, 0] } },
          emergency: { $sum: { $cond: [{ $eq: ['$type', 'emergency'] }, 1, 0] } },
          opd: { $sum: { $cond: [{ $eq: ['$type', 'OPD'] }, 1, 0] } },
          followUp: { $sum: { $cond: [{ $eq: ['$type', 'follow-up'] }, 1, 0] } },
          antenatal: { $sum: { $cond: [{ $eq: ['$type', 'antenatal'] }, 1, 0] } },
          vaccination: { $sum: { $cond: [{ $eq: ['$type', 'vaccination'] }, 1, 0] } },
        },
      },
    ]),
    Patient.countDocuments({
      ...centerFilter,
      createdAt: { $gte: start, $lte: end },
    }),
    Inventory.aggregate([
      { $match: centerFilter },
      { $unwind: '$restockHistory' },
      {
        $match: {
          'restockHistory.createdAt': { $gte: start, $lte: end },
          'restockHistory.operation': 'subtract',
        },
      },
      {
        $group: {
          _id: null,
          totalUsed: { $sum: '$restockHistory.quantity' },
          itemsCount: { $sum: 1 },
        },
      },
    ]),
  ]);

  const apptData = appointmentStats[0] || {};
  const invData = inventoryUsage[0] || {};

  // Gender split from completed appointments → linked patients
  const genderSplit = await Appointment.aggregate([
    { $match: { ...centerFilter, ...dateFilter, status: APPOINTMENT_STATUS.COMPLETED } },
    {
      $lookup: {
        from: 'patients',
        localField: 'patient',
        foreignField: '_id',
        as: 'patientData',
      },
    },
    { $unwind: '$patientData' },
    { $group: { _id: '$patientData.gender', count: { $sum: 1 } } },
  ]);

  const genderMap = {};
  genderSplit.forEach((g) => { genderMap[g._id] = g.count; });

  return {
    patientsServed: apptData.completed || 0,
    appointmentsCompleted: apptData.completed || 0,
    appointmentsCancelled: apptData.cancelled || 0,
    appointmentsNoShow: apptData.noShow || 0,
    newPatients,
    emergencyCases: apptData.emergency || 0,
    vaccinationsGiven: apptData.vaccination || 0,
    antenatalVisits: apptData.antenatal || 0,
    inventoryItemsUsed: invData.totalUsed || 0,
    malePatientsServed: genderMap['male'] || 0,
    femalePatientsServed: genderMap['female'] || 0,
    otherPatientsServed: genderMap['other'] || 0,
  };
};

/**
 * Generate and save a daily report for a centre.
 *
 * @param {string} centerId
 * @param {Date} [date=yesterday]
 * @returns {Promise<Report>}
 */
const generateDailyReport = async (centerId, date) => {
  const reportDate = date ? new Date(date) : new Date();
  if (!date) reportDate.setDate(reportDate.getDate() - 1); // default to yesterday

  const startDate = new Date(reportDate);
  startDate.setHours(0, 0, 0, 0);
  const endDate = new Date(reportDate);
  endDate.setHours(23, 59, 59, 999);

  // Skip if report already exists
  const existing = await Report.findOne({
    healthCenter: centerId,
    reportType: REPORT_TYPES.DAILY,
    'period.startDate': startDate,
  });

  if (existing) {
    logger.info(`Daily report already exists for centre ${centerId} on ${startDate.toDateString()}`);
    return existing;
  }

  const metrics = await aggregateMetrics(centerId, startDate, endDate);

  const report = await Report.create({
    healthCenter: centerId,
    reportType: REPORT_TYPES.DAILY,
    period: { startDate, endDate },
    metrics,
    status: REPORT_STATUS.DRAFT,
    isAutoGenerated: true,
  });

  logger.info(`Daily report generated for centre ${centerId}: ${report._id}`);
  return report;
};

/**
 * Generate a weekly report (aggregated from daily reports or raw data).
 *
 * @param {string} centerId
 * @param {Date} [weekStart] - Monday of the week. Defaults to last week.
 * @returns {Promise<Report>}
 */
const generateWeeklyReport = async (centerId, weekStart) => {
  let start;
  if (weekStart) {
    start = new Date(weekStart);
  } else {
    // Last Monday
    start = new Date();
    start.setDate(start.getDate() - start.getDay() - 6);
    start.setHours(0, 0, 0, 0);
  }

  const end = new Date(start);
  end.setDate(end.getDate() + 6);
  end.setHours(23, 59, 59, 999);

  const existing = await Report.findOne({
    healthCenter: centerId,
    reportType: REPORT_TYPES.WEEKLY,
    'period.startDate': start,
  });

  if (existing) {
    logger.info(`Weekly report already exists for centre ${centerId}.`);
    return existing;
  }

  const metrics = await aggregateMetrics(centerId, start, end);

  const report = await Report.create({
    healthCenter: centerId,
    reportType: REPORT_TYPES.WEEKLY,
    period: { startDate: start, endDate: end },
    metrics,
    status: REPORT_STATUS.DRAFT,
    isAutoGenerated: true,
  });

  logger.info(`Weekly report generated for centre ${centerId}: ${report._id}`);
  return report;
};

/**
 * Generate monthly reports for all active centres in a district.
 *
 * @param {string} district
 * @param {number} [month] - 0-based month index
 * @param {number} [year]
 * @returns {Promise<Report[]>}
 */
const generateMonthlyReportsForDistrict = async (district, month, year) => {
  const now = new Date();
  const m = month !== undefined ? month : now.getMonth() - 1;
  const y = year !== undefined ? year : (m < 0 ? now.getFullYear() - 1 : now.getFullYear());
  const adjustedMonth = ((m % 12) + 12) % 12;

  const start = new Date(y, adjustedMonth, 1, 0, 0, 0, 0);
  const end = new Date(y, adjustedMonth + 1, 0, 23, 59, 59, 999);

  const centers = await HealthCenter.find({ district, isActive: true }).select('_id');
  const reports = [];

  for (const center of centers) {
    try {
      const existing = await Report.findOne({
        healthCenter: center._id,
        reportType: REPORT_TYPES.MONTHLY,
        'period.startDate': start,
      });

      if (!existing) {
        const metrics = await aggregateMetrics(center._id.toString(), start, end);
        const report = await Report.create({
          healthCenter: center._id,
          reportType: REPORT_TYPES.MONTHLY,
          period: { startDate: start, endDate: end },
          metrics,
          status: REPORT_STATUS.DRAFT,
          isAutoGenerated: true,
        });
        reports.push(report);
      }
    } catch (err) {
      logger.error(`Failed to generate monthly report for centre ${center._id}: ${err.message}`);
    }
  }

  logger.info(`Generated ${reports.length} monthly reports for district: ${district}`);
  return reports;
};

module.exports = {
  aggregateMetrics,
  generateDailyReport,
  generateWeeklyReport,
  generateMonthlyReportsForDistrict,
};
