'use strict';

const mongoose = require('mongoose');
const { REPORT_TYPES, REPORT_STATUS } = require('../config/constants');

const MetricsSchema = new mongoose.Schema(
  {
    patientsServed: { type: Number, default: 0 },
    appointmentsCompleted: { type: Number, default: 0 },
    appointmentsCancelled: { type: Number, default: 0 },
    appointmentsNoShow: { type: Number, default: 0 },
    newPatients: { type: Number, default: 0 },
    emergencyCases: { type: Number, default: 0 },
    referralsMade: { type: Number, default: 0 },
    // Inventory
    inventoryItemsUsed: { type: Number, default: 0 },
    inventoryRestocks: { type: Number, default: 0 },
    inventoryValue: { type: Number, default: 0 },
    // Financial
    revenue: { type: Number, default: 0 },
    // Alerts
    outbreakAlerts: { type: Number, default: 0 },
    lowStockAlerts: { type: Number, default: 0 },
    expiryAlerts: { type: Number, default: 0 },
    // Disease breakdown (key-value)
    diseaseBreakdown: { type: Map, of: Number, default: {} },
    // Gender split
    malePatientsServed: { type: Number, default: 0 },
    femalePatientsServed: { type: Number, default: 0 },
    otherPatientsServed: { type: Number, default: 0 },
    // Vaccination
    vaccinationsGiven: { type: Number, default: 0 },
    // Antenatal
    antenatalVisits: { type: Number, default: 0 },
    // Bed occupancy
    averageBedOccupancy: { type: Number, default: 0 },
  },
  { _id: false }
);

const ReportSchema = new mongoose.Schema(
  {
    healthCenter: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'HealthCenter',
      required: [true, 'Health centre is required.'],
    },
    reportType: {
      type: String,
      enum: Object.values(REPORT_TYPES),
      required: [true, 'Report type is required.'],
    },
    period: {
      startDate: { type: Date, required: [true, 'Start date is required.'] },
      endDate: { type: Date, required: [true, 'End date is required.'] },
    },
    metrics: {
      type: MetricsSchema,
      default: () => ({}),
    },
    notes: {
      type: String,
      trim: true,
      default: null,
    },
    attachments: [
      {
        filename: { type: String },
        path: { type: String },
        uploadedAt: { type: Date, default: Date.now },
      },
    ],
    submittedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      default: null,
    },
    submittedAt: {
      type: Date,
      default: null,
    },
    status: {
      type: String,
      enum: Object.values(REPORT_STATUS),
      default: REPORT_STATUS.DRAFT,
    },
    approvedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      default: null,
    },
    approvedAt: {
      type: Date,
      default: null,
    },
    rejectionReason: {
      type: String,
      trim: true,
      default: null,
    },
    isAutoGenerated: {
      type: Boolean,
      default: false,
    },
  },
  {
    timestamps: true,
    toJSON: { virtuals: true },
    toObject: { virtuals: true },
  }
);

// ─── Indexes ──────────────────────────────────────────────────────────────────
ReportSchema.index({ healthCenter: 1 });
ReportSchema.index({ reportType: 1 });
ReportSchema.index({ status: 1 });
ReportSchema.index({ 'period.startDate': 1, 'period.endDate': 1 });
ReportSchema.index({ submittedBy: 1 });
// Prevent duplicate reports for same centre, type and period
ReportSchema.index(
  { healthCenter: 1, reportType: 1, 'period.startDate': 1 },
  { unique: true, sparse: true }
);

// ─── Virtual ─────────────────────────────────────────────────────────────────
ReportSchema.virtual('periodDays').get(function () {
  if (!this.period.startDate || !this.period.endDate) return 0;
  const diff = new Date(this.period.endDate) - new Date(this.period.startDate);
  return Math.ceil(diff / (1000 * 60 * 60 * 24));
});

module.exports = mongoose.model('Report', ReportSchema);
